name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: leofeilke
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Consumer Docker image
        run: docker build . --file docker/consumer.Dockerfile --tag consumer:latest

      - name: Build Producer Docker image
        run: docker build . --file docker/producer.Dockerfile --tag producer:latest

      - name: Push Consumer Docker image
        run: docker push leofeilke/consumer:latest

      - name: Push Producer Docker image
        run: docker push leofeilke/producer:latest
